name: Rebuild

on:
  schedule:
  - cron: * * * * *

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: netlify/actions/build@master
      secrets: ["GITHUB_TOKEN"]
      env:
      - NETLIFY_SITE_ID: 59ea48a5-7e88-45ea-852d-f6ea878a7fc4
